export const IMAGEANDTEXTDATA = [
    {
        key: 0,
        id: "boat",
        src: '/assets/images/thumbnails/boat.png',
        alt: 'A boat on the ocean',
        header: `Regular Admission: Travel by Boat`,
        text: 'The Jurassic Park ferry is a luxurious ocean liner ready to bring you safely to Isla Nublar.\nPlease check the ',
        textLink: 'ferry departure schedules',
        textHref: '/calendar-and-hours',
        text2: ' before your trip.',
        isOnRight: true,
    },
    {
        key: 1,
        id: "helicopter",
        src: "/assets/images/thumbnails/helicopter-thumbnail.png",
        alt: 'Helicopter over the ocean',
        header: 'VIP Admission: Travel by Helicopter',
        headerHref: '/tickets#VIP',
        text: 'Our VIP guests will enjoy a private ride over the ocean in our InGen helicopters. Before landing, guests will be able to view our gorgeous natural ',
        textHref: 'waterfalls',
        textLink: 'waterfalls',
        text2: ' from the helicopter windows.\nVIP guests who prefer are also able to take the ferry.',
    },
    {
        key: 2,
        src: "/assets/images/thumbnails/visitor-center/headphones.png",
        alt: "A person wearing headphones",
        header: "Assisted Listening Devices, Wheelchairs, & More",
        headerHref: "/accessibility",
        text: "The Visitor Center is also your one-stop shop for accessibility needs and info, including wheelchairs available for rent, assisted listening devices and noise-cancellation headphones, and more.",
    },
    {
        key: 3,
        src: "/assets/images/thumbnails/visitor-center/corporate-events.png",
        alt: "A group of people watching a PowerPoint presentation",
        header: "Corporate & Special Events",
        headerHref: "/groups#corporate-events",
        text: "Did you know that Jurassic Park is also perfect for corporate retreats and events? Call today to see if the Presentation Room in the Visitor Center is right for your team.",
        isOnRight: true,
    }
]