//export const ADD_CAFE_MENU = 'ADD_CAFE_MENU';
//export const CAFE_MENU_LOADING = 'CAFE_MENU_LOADING';
//export const CAFE_MENU_FAILED = 'CAFE_MENU_FAILED';

export const ADD_DINOSAURS = 'ADD_DINOSAURS';
export const DINOSAURS_LOADING = 'DINOSAURS_LOADING';
export const DINOSAURS_FAILED = 'DINOSAURS_FAILED';

